// templates/angular/ts/projects/empty/files/src/app/components/home.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-home',
	template: `
		<h2>Ignite UI CLI Project: $(name)</h2>
		<img src="src/app/assets/Ignite-header-apps-960.png" alt="Ignite UI" height="602" width="602" />
	`
})
export class HomeComponent {
	public projectName: string = "$(name)";
}

// packages/cli/templates/react/es6/projects/empty/files/client/pages/Home/index.js
import React from 'react';
import Header from 'components/Header';

export default () => (
  <article className="home">
    <Header title="$(description): $(name)" className="header-main" />
    <img src="https://static.infragistics.com/marketing/Website/products/ignite/Ignite-header-apps-960.png" alt="Ignite UI" height="402" width="402" />
  </article>
);
