// packages/cli/templates/react/es6/projects/empty/files/src/components/home/index.js
import React, { Component } from "react";

export default class Home extends Component {
  state = {};

  render() {
    return (
      <article>
        <h1>Welcome to Ignite UI for React Wrappers!</h1>
        <a
          href="https://github.com/IgniteUI/igniteui-react-wrappers"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img
            src="https://static.infragistics.com/marketing/Website/products/ignite/Ignite-header-apps-960.png"
            alt="Ignite UI"
            height="550"
            width="550"
          />
        </a>
      </article>
    );
  }
}

// packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  standalone: false
})
export class HomeComponent  {
  title = 'Welcome to Ignite UI for Angular!';
  constructor() { }
}

<!--The content below is only a placeholder and can be replaced.-->
<h1>{{title}}</h1>
<img src="assets/responsive.gif" alt="Ignite UI CLI">

<div id="linksContainer">
    <h3 class="links"><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/ignite-ui-cli">Ignite UI CLI </a></h3>
    <h3 class="links"><a target="_blank" rel="noopener" href="https://www.infragistics.com/products/ignite-ui-angular">Component Demos</a></h3>
    <h3 class="links"><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/igniteui-angular-ui-kits">Sketch UI Kit</a></h3>
</div>
