// packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  standalone: false
})
export class HomeComponent  {
  title = 'Welcome to Ignite UI for Angular!';
  constructor() { }
}

<!--The content below is only a placeholder and can be replaced.-->
<h1>{{title}}</h1>
<img src="assets/responsive.gif" alt="Ignite UI CLI">

<div id="linksContainer">
    <h3 class="links"><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/ignite-ui-cli">Ignite UI CLI </a></h3>
    <h3 class="links"><a target="_blank" rel="noopener" href="https://www.infragistics.com/products/ignite-ui-angular">Component Demos</a></h3>
    <h3 class="links"><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/igniteui-angular-ui-kits">Sketch UI Kit</a></h3>
</div>

// packages/cli/templates/react/igr-ts/projects/_base/files/src/app/home/home.tsx
import logo from "/logo.svg";
import styles from "./style.module.css";

export default function Home() {
  const name = '$(name)';

  return (
    <div className="app">
      <div className={styles.app__name}>{name}</div>
      <header className={styles.header}>
        <img src={logo} className={styles.logo} alt="logo" />
        <p>Welcome to Ignite UI for React!</p>
        <a
          className={styles.link}
          target="_blank"
          href="https://www.infragistics.com/products/ignite-ui-react"
          rel="noopener noreferrer"
        >
          Learn More
        </a>
      </header>
    </div>
  );
}
