// packages/cli/templates/react/igr-ts/projects/top-nav/files/src/App.tsx
import { Route, Routes } from "react-router-dom";
import NavigationHeader from "./components/navigation-header/index";
import { routes } from './routes';
import "./App.css";

export default function App() {
	const name = "$(name)";
	return (
			<div className="app">
        <div className="app__name">{name}</div>
          <NavigationHeader routes={routes}></NavigationHeader>
          <div className="content">
            <Routes>
              {routes.map((route, i) => (
                <Route key={i} path={route.path} element={route.element} />
              ))}
            </Routes>
          </div>
			</div>
	);
}

// packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts
import { LitElement, html, customElement } from 'lit-element';
import 'igniteui-webcomponents';
import { routes } from './index';
import './app/home/home-component';
import './app/not-found/not-found.component';

@customElement('lit-app')
export class App extends LitElement {
  render() {
    return html`
    <div id="navigation-outlet">
      <igc-nav-drawer open=true>
        <igc-nav-drawer-header-item>Ignite UI CLI</igc-nav-drawer-header-item>

        ${routes.map(i => html`
          <igc-nav-drawer-item>
            <span slot="content">
              <a href="${i.path}">${i.name}</a>
            </span>
          </igc-nav-drawer-item>
        `)}
      </igc-nav-drawer>
    </div>
    `;
  }
}
