// packages/cli/templates/react/igr-es6/projects/_base/files/src/views/home/index.js
import React from 'react';
import logo from './logo.svg';
import styles from './style.css';

export default function Home() {
	return (
		<header className={styles.header}>
			<img src={logo} className={styles.logo} alt="logo" />
			<p>
			Welcome to Ignite UI for React!
			</p>
			<a
			className={styles.link}
			href="https://www.infragistics.com/products/ignite-ui-react"
			target="_blank"
			rel="noopener noreferrer"
			>
			Learn More
			</a>
		</header>
	)
}

// templates/angular/igx-ts/projects/empty/files/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  title = '$(name)';
  constructor() { }

  ngOnInit() {
  }

}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
  <img src="assets/responsive.gif" alt="Ignite UI CLI">
</div>

<ul id="linksContainer">
  <li class="links">
    <h3><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/ignite-ui-cli">Ignite UI CLI </a></h3>
  </li>
  <li class="links">
      <h3><a target="_blank" rel="noopener" href="https://www.infragistics.com/products/ignite-ui-angular">Component Demos</a></h3>
  </li>
  <li class="links">
    <h3><a target="_blank" rel="noopener" href="https://github.com/IgniteUI/igniteui-angular-ui-kits">Sketch UI Kit</a></h3>
  </li>
</ul>
