// packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/src/app/home/home.ts
import { html, css, LitElement } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-home')
export class HomeComponent extends LitElement {
  static styles = css`
    p {
      margin: 0px 0px 8px 0px;
    }
    img {
      margin-bottom: 48px;
      max-height: 480px;
      max-width: 100%;
    }
  `;

  render() {
    return html`
      <h1>Welcome to Ignite UI for Web Components!</h1>
      <h4>A complete library of UI components, giving you the ability to build modern web applications using encapsulation and the concept of reusable components in a dependency-free approach.</h4>
      <img src="./src/assets/astronaut-components.svg" alt="indigoDesign">
      <p class="ig-typography__subtitle-1">Discover more at</p>
      <p>
        <a href="https://www.infragistics.com/products/ignite-ui-web-components" target="_blank">
          www.infragistics.com/products/ignite-ui-web-components
        </a>
      </p>
      <p>
        <a href="https://www.infragistics.com/products/indigo-design" target="_blank">
          www.infragistics.com/products/indigo-design
        </a>
      </p>
      <p class="ig-typography__subtitle-1">We are also on GitHub</p>
      <p class="content__container--wide">
        <a href="https://github.com/IgniteUI/igniteui-cli" target="_blank">
          <span class="content__link-image"></span>Ignite UI CLI
        </a>
      </p>
    `;
  }
}

// packages/cli/templates/react/igr-ts/projects/_base_with_home/files/src/app/home/home.tsx
import logo from "/logo.svg";
import githubLogo from "/github.svg";
import styles from "./style.module.css";

export default function App() {
  return (
    <main className={styles.content}>
      <h1 className={styles.header}>Welcome to Ignite UI for React!</h1>
      <h4 className={styles.subject}>
        A complete library of 50+ UI components for building modern web applications with reusable React components.
      </h4>
      <img src={logo} className={styles.logo} alt="Ignite UI for React" />

      <p className={styles.subtitle}>Discover more at</p>
      <p>
        <a
          className={styles.link}
          target="_blank"
          href="https://www.infragistics.com/products/ignite-ui-react"
          rel="noopener noreferrer"
        >
          www.infragistics.com/products/ignite-ui-react
        </a>
      </p>
      <p>
        <a
          className={styles.link}
          target="_blank"
          href="https://www.infragistics.com/products/indigo-design"
          rel="noopener noreferrer"
        >
          www.infragistics.com/products/indigo-design
        </a>
      </p>

      <p className={styles.subtitle}>We are also on GitHub</p>
      <p className={styles.githubLinks}>
        <a
          className={styles.githubLink}
          target="_blank"
          href="https://github.com/IgniteUI/igniteui-react"
          rel="noopener noreferrer"
        >
          <img src={githubLogo} alt="" />
          Ignite UI for React
        </a>
        <a
          className={styles.githubLink}
          target="_blank"
          href="https://github.com/IgniteUI/igniteui-cli"
          rel="noopener noreferrer"
        >
          <img src={githubLogo} alt="" />
          Ignite UI CLI
        </a>
      </p>
    </main>
  );
}
