// packages/igx-templates/igx-ts/projects/empty/files/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {
}

<div class="content">
  <h1 class="content__header content__subject">Welcome to Ignite UI for Angular!</h1>
  <h4 class="content__subject">50+ Material-based UI Components</h4>
  <img src="../../assets/indigo-design.svg" class="content__image">
  <p class='igx-typography__subtitle-1'>Discover more at</p>
  <p>
    <a href='http://www.infragistics.com/products/ignite-ui-angular' target="_blank" class='content__link igx-typography__body-2'>
      http://www.infragistics.com/products/ignite-ui-angular</a>
  </p>
  <p>
    <a href="http://www.infragistics.com/products/indigo-design" target="_blank" class='content__link igx-typography__body-2'>
      http://www.infragistics.com/products/indigo-design
    </a></p>
  <p class='igx-typography__subtitle-1'>We are also on GitHub</p>
  <p class="content__container--wide">
    <a href="https://github.com/IgniteUI/igniteui-angular" target="_blank" class="content__link--github igx-typography__body-2">
      <span class="content__link-image"></span>Ignite UI for Angular
    </a>
    <a href="https://github.com/IgniteUI/igniteui-cli" target="_blank" class="content__link--github igx-typography__body-2">
      <span class="content__link-image"></span>Ignite UI CLI
    </a>
  </p>
</div>

// packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app/home/HomeComponent.ts
import { LitElement, html, css, customElement } from 'lit-element';

@customElement('lit-home')
export class HomeComponent extends LitElement {
  static styles = css`
    p {
      margin: 0px 0px 8px 0px;
    }
    img {
      margin-bottom: 48px;
      max-height: 480px;
      max-width: 100%;
    }
  `;

  render() {
    return html`
      <h1>Welcome to Ignite UI for Web Components!</h1>
      <h4>A complete library of UI components, giving you the ability to build modern web applications using encapsulation and the concept of reusable components in a dependency-free approach.</h4>
      <img src="./src/assets/astronaut-components.svg" alt="indigoDesign">
      <p class="igx-typography__subtitle-1">Discover more at</p>
      <p>
        <a href="https://www.infragistics.com/products/ignite-ui-web-components" target="_blank">
          www.infragistics.com/products/ignite-ui-web-components
        </a>
      </p>
      <p>
        <a href="https://www.infragistics.com/products/indigo-design" target="_blank">
          www.infragistics.com/products/indigo-design
        </a>
      </p>
      <p class="igx-typography__subtitle-1">We are also on GitHub</p>
      <p class="content__container--wide">
        <a href="https://github.com/IgniteUI/igniteui-cli" target="_blank">
          <span class="content__link-image"></span>Ignite UI CLI
        </a>
      </p>
    `;
  }
}
